package cmd

import (
	"fmt"
	"html/template"
	"strings"
)

// renderHistoricalEvents generates a self-contained HTML fragment (details/summary + table)
// for the given events slice. Returns an empty string when events is nil or empty.
func renderHistoricalEvents(events []historicalEvent) template.HTML {
	if len(events) == 0 {
		return ""
	}

	var sb strings.Builder

	sb.WriteString(`<details class="historical-events">
  <summary class="historical-events__summary">Historical Events During Lifetime</summary>
  <div class="historical-events__content">
    <table class="historical-events__table">
      <thead>
        <tr>
          <th scope="col">Date</th>
          <th scope="col">Event</th>
          <th scope="col">Location</th>
        </tr>
      </thead>
      <tbody>
`)

	for _, e := range events {
		location := e.Location
		if location == "" {
			location = "—"
		}
		description := e.Description
		if description != "" {
			description = fmt.Sprintf(` title="%s"`, template.HTMLEscapeString(description))
		}
		sb.WriteString(fmt.Sprintf(`        <tr>
          <td><time datetime="%s">%s</time></td>
          <td%s>%s</td>
          <td>%s</td>
        </tr>
`,
			template.HTMLEscapeString(e.Date),
			template.HTMLEscapeString(e.Date),
			description,
			template.HTMLEscapeString(e.Title),
			template.HTMLEscapeString(location),
		))
	}

	sb.WriteString(`      </tbody>
    </table>
  </div>
</details>
`)

	return template.HTML(sb.String()) // #nosec G203 – all user data is HTML-escaped above
}

// historicalEventsCSSContent holds the CSS for styling the historical events section.
// It is written to static/css/history-events.css in the Hugo project.
const historicalEventsCSSContent = `/* =====================================================================
   Historical Events – genealogy-themed stylesheet
   Generated by gedcom2hugo
   ===================================================================== */

/* Container --------------------------------------------------------- */
.historical-events {
  margin-top: 2rem;
  border: 1px solid #c8b89a;
  border-radius: 6px;
  background: #fdf6ec;
  overflow: hidden;
}

/* Summary bar ------------------------------------------------------- */
.historical-events__summary {
  display: flex;
  align-items: center;
  padding: 0.75rem 1.25rem;
  background: linear-gradient(135deg, #7a5230 0%, #a0722a 100%);
  color: #fff;
  font-weight: 600;
  font-size: 1rem;
  letter-spacing: 0.03em;
  cursor: pointer;
  user-select: none;
  list-style: none;
  gap: 0.5rem;
}

.historical-events__summary::-webkit-details-marker,
.historical-events__summary::marker {
  display: none;
}

.historical-events__summary::before {
  content: "▶";
  font-size: 0.7em;
  transition: transform 0.2s ease;
}

.historical-events[open] > .historical-events__summary::before {
  transform: rotate(90deg);
}

/* Content area ------------------------------------------------------ */
.historical-events__content {
  padding: 1rem;
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
}

/* Table ------------------------------------------------------------- */
.historical-events__table {
  width: 100%;
  border-collapse: collapse;
  font-size: 0.9rem;
  background: #fff;
  border-radius: 4px;
  overflow: hidden;
  box-shadow: 0 1px 4px rgba(120, 80, 40, 0.08);
}

.historical-events__table thead {
  background: #f0e8d8;
}

.historical-events__table th {
  padding: 0.6rem 1rem;
  text-align: left;
  color: #5a3e1b;
  font-weight: 700;
  font-size: 0.85rem;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  border-bottom: 2px solid #c8b89a;
}

.historical-events__table td {
  padding: 0.5rem 1rem;
  border-bottom: 1px solid #ede4d3;
  vertical-align: top;
  color: #3a2c1a;
  line-height: 1.45;
}

.historical-events__table tbody tr:last-child td {
  border-bottom: none;
}

.historical-events__table tbody tr:hover td {
  background: #fdf0dc;
}

.historical-events__table time {
  white-space: nowrap;
  font-variant-numeric: tabular-nums;
  color: #7a5c1e;
  font-weight: 500;
  font-family: ui-monospace, "SFMono-Regular", Consolas, monospace;
}

/* Responsive: stack cells on small screens ------------------------- */
@media (max-width: 600px) {
  .historical-events__table thead {
    display: none;
  }

  .historical-events__table tbody tr {
    display: block;
    margin-bottom: 0.75rem;
    border: 1px solid #e0d0b8;
    border-radius: 4px;
    padding: 0.5rem 0.75rem;
    background: #fff;
  }

  .historical-events__table td {
    display: block;
    border: none;
    padding: 0.25rem 0;
  }

  .historical-events__table td:nth-child(1)::before {
    content: "📅 ";
  }

  .historical-events__table td:nth-child(2)::before {
    content: "📌 ";
    font-style: normal;
  }

  .historical-events__table td:nth-child(3)::before {
    content: "🌍 ";
  }
}
`
